ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name='cart'
urlpatterns = [path('addtocart/<int:i>',views.add_to_cart,name='add_to_cart'),
               path('cartview',views.cartview,name='cartview'),
               path('cartminus/<int:i>',views.cart_minus,name='cartminus'),
               path('carttrash/<int:i>',views.cart_trash,name='carttrash'),
               path('placeorder',views.place_order,name='placeorder'),
               path('status/<u>',views.payment_status,name='status'),
               path("orderview",views.order_view,name="orderview"),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('search/',include('search.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name='search'

urlpatterns = [
    path('search_products',views.search_products,name="search_products"),
]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name='shop'

urlpatterns = [
    path('',views.category,name='category'),
    path('product/<int:i>',views.product,name='product'),
    path('productdetails/<int:i>',views.productdetails,name='productdetails'),
    path('register',views.register,name="register"),
    path('userlogin',views.user_login,name='userlogin'),
    path('userlogout',views.user_logout,name='userlogout'),
]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User

class Cart(models.Model):
    product=models.ForeignKey(Product,models.CASCADE)
    user=models.ForeignKey(User,models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name

    def subtotal(self):
        return self.quantity*self.product.price

class Order(models.Model):
    user=models.ForeignKey(User,models.CASCADE)
    product=models.ForeignKey(Product,models.CASCADE)
    no_of_items=models.IntegerField()
    phone=models.BigIntegerField(default=0)
    address=models.TextField(default="")
    pincode=models.IntegerField()
    landmark=models.CharField(max_length=30)
    ordered_date=models.DateTimeField(auto_now_add=True)
    order_id=models.CharField(max_length=100,blank=True)
    payment_status=models.CharField(default="pending",max_length=30)
    delivery_status=models.CharField(default="pending",max_length=30)


    def __str__(self):
        return self.user.username

class Payment(models.Model):
    name=models.CharField(max_length=100)
    amount=models.IntegerField()
    order_id=models.CharField(max_length=100,blank=True)
    razorpay_payment_id=models.CharField(max_length=100,blank=True)
    paid=models.BooleanField(default=False)

    def __str__(self):
        return self.name

ecommerce/cart/views.py
from django.shortcuts import render,redirect
from shop.models import Product
from cart.models import Cart,Payment,Order
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.http import HttpResponse

@login_required
def add_to_cart(request,i):
    p=Product.objects.get(id=i)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(p.stock>0):
            cart.quantity += 1
            cart.save()
            p.stock -= 1
            p.save()
    except:
        if(p.stock):
            cart=Cart.objects.create(product=p,user=u,quantity=1)
            cart.save()
            p.stock -= 1
            p.save()

    return redirect('cart:cartview')

@login_required
def cartview(request):
    u=request.user
    cart=Cart.objects.filter(user=u)
    total=0
    for i in cart:
        total=total+(i.quantity*i.product.price)
    return render(request,'cart.html',{'cart':cart,'total':total})


def cart_minus(request,i):
    p=Product.objects.get(id=i)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(cart.quantity > 1):
            cart.quantity -= 1
            cart.save()
            p.stock += 1
            p.save()
        else:
            cart.delete()
            p.stock += 1
            p.save()
    except:
        pass
    return redirect('cart:cartview')

def cart_trash(request,i):
    p=Product.objects.get(id=i)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        cart.delete()
        p.stock += cart.quantity
        p.save()
    except:
        pass
    return redirect('cart:cartview')

import razorpay
def place_order(request):
    if(request.method=="POST"):
        phone=request.POST["ph"]
        address=request.POST["a"]
        pincode=request.POST["pin"]
        landmark=request.POST["lm"]
        u=request.user
        cart=Cart.objects.filter(user=u)
        total=0
        for i in cart:
            total=total+(i.quantity*i.product.price)
        total=int(total*100)
        client=razorpay.Client(auth=("rzp_test_vagvUoVPzlml2k","2UyeeuxtqPMhUfwUzduEZWG4"))
        response_payment=client.order.create(dict(amount=total,currency='INR'))
        print(response_payment)
        order_id=response_payment['id']
        order_status=response_payment['status']
        if order_status=='created':
            payment=Payment.objects.create(name=u.username,amount=total,order_id=order_id)
            payment.save()
            for i in cart:
                o=Order.objects.create(user=u,product=i.product,no_of_items=i.quantity,phone=phone,address=address,pincode=pincode,landmark=landmark,order_id=order_id)
                o.save()
        response_payment['name']=u.username
        return render(request,"payment.html",{"payment":response_payment})
    return render(request,'placeorder.html',{})

@csrf_exempt
def payment_status(request,u):
    if(not request.user.is_authenticated):
        u = User.objects.get(username=u)
        login(request,u)
    if(request.method=="POST"):
        response=request.POST
        print(response)
        param_dict={
            "razorpay_order_id":response["razorpay_order_id"],
            "razorpay_payment_id":response["razorpay_payment_id"],
            "razorpay_signature":response["razorpay_signature"]
        }
        client=razorpay.Client(auth=("rzp_test_vagvUoVPzlml2k","2UyeeuxtqPMhUfwUzduEZWG4"))
        try:
            status=client.utility.verify_payment_signature(param_dict)
            print(status)
            ord=Payment.objects.get(order_id=response["razorpay_order_id"])
            ord.razorpay_payment_id=response["razorpay_payment_id"]
            ord.paid=True
            ord.save()
            u=User.objects.get(username=u)
            c=Cart.objects.filter(user=u)
            o=Order.objects.filter(user=u,order_id=response["razorpay_order_id"])
            for i in o:
                i.payment_status="paid"
                i.save()
            c.delete()
            return render(request,"status.html",{'status':True})

        except:
            return render(request, "status.html", {'status': False})

@login_required()
def order_view(request):
    u=request.user
    o=Order.objects.filter(user=u,payment_status="paid")
    return render(request,"orders.html",{"orders":o})

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    <title>Title</title>
    {% endblock %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/js1.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="wrapper d-flex flex-column min-vh-100">
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <img src="{% static 'images/shopping-cart.png' %}" height="3%" width="3%" class="logo pb-1">
            <a class="navbar-brand" href="#"> ShOpkart</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'shop:category' %}">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            All Categories
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% for i in links %}
                            <li><a class="dropdown-item" href="{% url 'shop:product' i.id %}">{{i.name}}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                    {% if user.is_authenticated %}
                                          <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Logged in as: {{user.username}}</a>
                    </li>
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'shop:userlogout' %}">Logout</a>
                    </li>
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-bag-shopping"></i><b><sup>{{count}}</sup></b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'cart:orderview' %}">My Orders</a>
                    </li>
                    {% else %}
                     <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'shop:register' %}">Register</a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'shop:userlogin' %}">Login</a>
                    </li>
                   {% endif %}
                </ul>
                <form class="d-flex" method="post" action="{% url 'search:search_products' %}">
                    {% csrf_token %}
                    <input class="form-control me-2" type="search" name="q" placeholder="Search for Products" aria-label="Search">
                    <button class="btn btn-primary" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
</header>
    <main class="flex-fill">
{% block content %}
{% endblock %}
    </main>
<br>
<footer class="footer bg-light mt-auto py-3">
    <div class="container-fluid" style="height:100px; width:100%;">

        <center><p class="mt-5">Copyright ©2024 ShOpkart. All Rights Reserved</p></center>
    </div>
</footer>
    </div>
</body>
</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Cart</title>
{% endblock %}
{% block content %}
<div class="container-fluid">
<center><h2 class="mt-4">Your Cart</h2></center>
    <br>
<h5 class="ms-4">{{num}} items</h5>
<hr>
<div class="row">
    <div class="col-sm-8">
        <div class="container">
        <table class=" table table-bordered table-hover">
            <tr><th colspan="6">Cart Items</th></tr>
            {% for i in cart %}
            <tr><td><img src="{{i.product.image.url}}" height="150px" width="auto" ></td>
            <td>{{i.product.name}}</td>
            <td class="fw-bold">Product id: {{i.product.id}}</td>
            <td class="fw-bold">Quantity: {{i.quantity}}<br>Unit Price: {{i.quantity}}x₹{{i.product.price}}</td>
            <td class="fw-bold">Subtotal: ₹{{i.subtotal}}</td>
                {% if i.product.stock > 0 %}
            <td><a href="{% url 'cart:add_to_cart' i.product.id %}"><i class="fa-solid fa-circle-plus" style="color: #000000;"></i></a><br>
            <a href="{% url 'cart:cartminus' i.product.id %}"><i class="fa-solid fa-circle-minus" style="color: #000000;"></i></a><br>
            <a href="{% url 'cart:carttrash' i.product.id %}"><i class="fa-solid fa-trash-can" style="color: #030303;"></i></a></td></tr>
            {% else %}
            <a href="{% url 'cart:cartminus' i.product.id %}"><i class="fa-solid fa-circle-minus" style="color: #000000;"></i></a>
            <a href="{% url 'cart:carttrash' i.product.id %}"><i class="fa-solid fa-trash-can" style="color: #030303;"></i></a></td></tr>
            {% endif %}
            {% endfor %}
        </table></div>
    </div>
    <div class="col-sm-4">

         <div class="container">

        <table class="table table-bordered">
            <tr><th colspan="4">Checkout</th></tr>
            <tr><th colspan="4">Total Amount: {{total}}</th></tr>
        </table>

             <a href="{% url 'cart:placeorder' %}" class="btn btn-warning" style="width:300px;border-radius:20px;">Place Order</a><br>
             <a href="{% url 'shop:category' %}" class="btn btn-danger mt-3" style="width:300px;border-radius:20px;">Continue Shopping</a>
    </div>
    </div>

</div>
</div>

{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>ShOpkart Home</title>
{% endblock %}
{% block content %}
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'images\IMG_9606.JPG' %}" height="600px" width="100%" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'images\IMG_9607.JPG' %}" height="600px" width="100%" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'images\IMG_9608.JPG' %}" height="600px" width="100%" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
<br>
<center><h2>Our Collections</h2>
  <div class="container">
<p>Explore our exclusive collections, where timeless elegance meets modern style. Discover a curated selection of premium products crafted to elevate your lifestyle. From sophisticated fashion to luxurious home décor, each piece is designed with impeccable attention to detail. Elevate your everyday with our carefully curated offerings.</p></div></center>
<div class="container">
  <div class="row">
    {% for i in items %}
    <div class="col-sm-3 mt-4"><div class="card mx-auto" style="width: 18rem;">
  <img src="{{ i.image.url }}" width="auto" height="250px" class="card-img-top" alt="product image">
  <div class="card-body d-flex flex-column justify-content-between">
    <h5 class="card-title text-center">{{i.name}}</h5>
    <p class="card-text text-center fw-bold">{{i.offprice}}</p>
    <div class="mt-auto">
    <center><a href="{% url 'shop:product' i.id %}" class="btn btn-primary">Shop Now</a></center></div>
  </div>
</div></div>
    {% endfor %}
  </div>
</div>
{% endblock %}

ecommerce/templates/orders.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Cart</title>
{% endblock %}
{% block content %}
<div class="container-fluid">
<center><h2 class="mt-4">Your Orders</h2></center>
    <br>
<hr>
<div class="row">
    {% for i in orders %}
    <div class="col-sm-5">
<img src="{{i.product.image.url}}" height="150px" width="150px">
    </div>
    <div class="col-sm-6">
        <p><b>Delivery status : {{i.delivery_status}}</b></p>
       <p>Order Date & Time : {{i.ordered_date}}</p>
<p>{{i.product.name}}</p>
        <p>₹{{i.product.price}}</p>
        <p>Quantity : {{i.no_of_items}}</p>
    </div>
    <hr class="mt-4">
{% endfor %}
</div>
</div>

{% endblock %}

ecommerce/templates/payment.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Place Order</title>
{% endblock %}
{% block content %}
<center><div class="bg-dark shadow-lg rounded mt-5 mb-5 pt-3 pb-5" style="width:500px;height:300px;"><h1 class="mt-5 mb-5 text-light">Make Payment</h1>
    <form action="http://127.0.0.1:8000/cart/status/{{payment.name}}" method="POST">
        {% csrf_token %}
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_vagvUoVPzlml2k"
    data-amount="{{payment.amount}}"
    data-currency="{{payment.currency}}"
    data-order_id="{{payment.id}}"
    data-buttontext="Pay with Razorpay"
    data-name="ShOpkart"
    data-description="Get all u want!!!"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="{{payment.name}}"
    data-prefill.email="gaurav.kumar@example.com"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>
</div>
</center>
{% endblock %}

ecommerce/templates/placeorder.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Place Order</title>
{% endblock %}
{% block content %}
<center><div class="bg-dark shadow-lg rounded mt-5 mb-5 pt-3 pb-5" style="width:700px;height:auto;"><h1 class="mt-5 text-light">Enter Details</h1>
    <br>
<form method="post">
    {% csrf_token %}
    <div class="mb-3">
    <label class="form-label text-light">Phone  number</label>
    <input class="form-control" type="number" placeholder="Enter Phone number" name="ph"></div>
        <div class="mb-3">
    <label class="form-label text-light">Delivery Address</label>
            <textarea rows="5" class="form-control" placeholder="Enter Address" name="a"></textarea></div>
        <div class="mb-3">
             <label class="form-label text-light">Pincode</label>
    <input class="form-control" type="number" placeholder="Enter Pincode" name="pin"></div>
        <div class="mb-3">
    <label class="form-label text-light">Landmark</label>
    <input class="form-control" type="text" placeholder="Enter Nearest Landmark" name="lm"></div>
        <div class="mb-3">
    <input class="form-control btn-warning" type="submit" value="Continue"></div>
</form>
</div>
</center>
{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Product</title>
{% endblock %}
{% block content %}
<div class="container">

<center><img src="{{item.image.url}}" height="20%" width="50%" class="image" alt="image">
  <h2 class="mt-2">{{item.name}}</h2>
<p>{{item.desc}}</p></center></div>
<div class="container">
  <div class="row">
    {% for i in product %}
    <div class="col-sm-3 mt-4"><div class="card mx-auto" style="width: 18rem;height:430px">
  <img src="{{ i.image.url }}" width="auto" height="250px" class="card-img-top" alt="product image">
  <div class="card-body d-flex flex-column justify-content-between">
    <h5 class="card-title text-center">{{i.name}}</h5>
    <p class="card-text text-center fw-bold">₹{{i.price}}</p>
    <div class="mt-auto">
    <center><a href="{% url 'shop:productdetails' i.id %}" class="btn btn-primary">Shop Now</a></center></div>
  </div>
</div></div>
    {% endfor %}
  </div>
</div>

{% endblock %}

ecommerce/templates/productdetails.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Product details</title>
{% endblock %}
{% block content %}
<div class="container">
<center><img src="{{product.image.url}}" height="20%" width="50%" class="image" alt="image">
    <h2>{{product.name}}</h2>
    <h6 class="fw-bold">₹{{product.price}}</h6>
    <h6>Available Stock:{{product.stock}}</h6>
    <p class="text-justify"><h4>Product Details</h4>{{product.desc}}</p>
</center>
    {% if user.is_superuser %}
    {% if product.stock > 0 %}
    <center><h4 class="text-success">In Stock</h4></center>
    <div class="row mt-4">
        <div class="col-sm-5 "></div>
    <div class="col-sm-2 "><a href="{% url 'admin:index' %}" class="btn btn-warning ms-5">ADD STOCK</a></div>
    <div class="col-sm-5 "></div></div>
        {% else %}
            <center><h4 class="text-danger">Out of Stock</h4></center>
    <div class="row mt-4">
            <div class="col-sm-5 "></div>
    <div class="col-sm-2 "><a href="{% url 'admin:index' %}" class="btn btn-warning ms-5">ADD STOCK</a></div>
    <div class="col-sm-5 "></div></div>
        {% endif %}
        {% else %}
        {% if product.stock > 0 %}
        <center><h4 class="text-success">In Stock</h4></center>
<div class="row mt-4">
    <div class="col-sm-5 "></div>
        <div class="col-sm-2 "><a href="{% url 'cart:add_to_cart' product.id %}" style="position: relative; left: 35px;" class="btn btn-warning">ADD TO CART</a></div>
    <div class="col-sm-5 "></div></div>
    {% else %}
    <center><h4 class="text-danger">Out of Stock</h4></center>
    {% endif %}
    {% endif %}
</div>
{% endblock %}

ecommerce/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Registration</title>
{% endblock %}
{% block content %}
<center><h1 class="mt-2">Looks like you're new here!</h1>
<p class='mt-1'>Sign up to get started</p>
    <br>
<form method="post">
    {% csrf_token %}
    <div class="mb-3">
    <label class="form-label">Username</label>
    <input class="form-control" type="text" placeholder="Enter username" name="u"></div>
        <div class="mb-3">
    <label class="form-label">Password</label>
    <input class="form-control" type="password" placeholder="Enter password" name="p"></div>
        <div class="mb-3">
             <label class="form-label">Confirm Password</label>
    <input class="form-control" type="password" placeholder="Confirm your password" name="cp"></div>
        <div class="mb-3">
    <label class="form-label">First Name</label>
    <input class="form-control" type="text" placeholder="Enter first name" name="fn"></div>
        <div class="mb-3">
            <label class="form-label">Last Name</label>
    <input class="form-control" type="text" placeholder="Enter last name" name="ln"></div>
        <div class="mb-3">
                   <label class="form-label">Email</label>
    <input class="form-control" type="email" placeholder="Enter email" name="em"></div>
        <div class="mb-3">
    <input class="form-control btn-warning" type="submit" value="Sign Up"></div>
</form>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</center>
{% endblock %}

ecommerce/templates/searchres.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>search result</title>
{% endblock %}
{% block content %}
<center><h4>you have searched for {{query}}</h4>
{% if product == None %}
<p>No result found</p></center>
{% else %}
<div class="container">
<div class="container">
  <div class="row">
    {% for i in product %}
    <div class="col-sm-3 mt-4"><div class="card mx-auto" style="width: 18rem;height:430px">
  <img src="{{ i.image.url }}" width="auto" height="250px" class="card-img-top" alt="product image">
  <div class="card-body d-flex flex-column justify-content-between">
    <h5 class="card-title text-center">{{i.name}}</h5>
    <p class="card-text text-center fw-bold">₹{{i.price}}</p>
    <div class="mt-auto">
    <center><a href="{% url 'shop:productdetails' i.id %}" class="btn btn-primary">Shop Now</a></center></div>
  </div>
</div></div>
        {% empty %}
    <p class="text-center">no result found</p>
    {% endfor %}
  </div>
</div></div>
{% endif %}
{% endblock %}

ecommerce/templates/status.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Place Order</title>
{% endblock %}
{% block content %}
{% if status == True %}
<center><div class="bg-dark shadow-lg rounded mt-5 mb-5 pt-3 pb-5" style="width:500px;height:300px;"><h1 class="mt-5 mb-5 text-light">Payment Successfull</h1>
</div>
</center>
{% else %}
<center><div class="bg-dark shadow-lg rounded mt-5 mb-5 pt-3 pb-5" style="width:500px;height:300px;"><h1 class="mt-5 mb-5 text-light">Payment Unsuccessfull</h1>
</div>
</center>
{% endif %}
{% endblock %}

ecommerce/templates/userlogin.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Login</title>
{% endblock %}
{% block content %}
<center><h1 class="mt-2">Login</h1>
<p class='mt-1'>Get access to your Orders, Wishlist and Recommendations</p>
    <br>
<form method="post">
    {% csrf_token %}
    <div class="mb-3">
    <label class="form-label">Username</label>
    <input class="form-control" type="text" placeholder="Enter username" name="u"></div>
        <div class="mb-3">
    <label class="form-label">Password</label>
    <input class="form-control" type="password" placeholder="Enter password" name="p"></div>
        <div class="mb-3">
    <input class="form-control btn-warning" type="submit" value="Sign In"></div>
</form>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
    {% endif %}

</center>
{% endblock %}